In [1]:
import torch
torch.__version__

/Users/jeannie/Documents/GitHub/repos/ml-intuition/learn-pytorch/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:307: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


'2.11.0'

## Basics: scalars -> vectors -> matrices -> tensors

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor(
    [
        [7,8],
        [9,10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
])
TENSOR
print(f"{TENSOR.ndim=}")
print(f"{TENSOR.shape=}")

TENSOR.ndim=3
TENSOR.shape=torch.Size([1, 3, 3])


## Random tensors, zero tensors, ones tensors

In [13]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.6605, 0.5743, 0.0185, 0.8207],
         [0.2551, 0.9097, 0.8133, 0.2726],
         [0.9309, 0.0629, 0.5968, 0.2846]]),
 torch.float32)

In [15]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.ndim, random_image_size_tensor.dtype

(3, torch.float32)

In [16]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [18]:
zero_to_ten = torch.arange(0, 10, 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeros = torch.zeros_like(input=zero_to_ten) # mocking the same shape as the zero_to_ten tensor
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [21]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None, # defaults to None. torch.float32
    device=None, # defaults to None, using the default tensor type
    requires_grad=False # if True, operations performed on the tensor are recorded
)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [22]:
float_16_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float16 # torch.half also works
)
float_16_tensor.dtype

torch.float16

## Finding out details

In [23]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"{some_tensor.shape=}")
print(f"{some_tensor.dtype=}")
print(f"{some_tensor.device=}")

tensor([[0.4844, 0.0439, 0.8052, 0.2640],
        [0.8606, 0.3264, 0.4712, 0.4204],
        [0.6529, 0.4295, 0.3160, 0.5547]])
some_tensor.shape=torch.Size([3, 4])
some_tensor.dtype=torch.float32
some_tensor.device=device(type='cpu')


In [ ]:
# little song: what, what, where? what shape, what datatype, what device?

## Manipulating tensors (operations!)

In [24]:
tensor = torch.tensor([1, 2, 2])
tensor + 10

tensor([11, 12, 12])

In [25]:
tensor * 10

tensor([10, 20, 20])

In [26]:
tensor
# tensors don't change unless reassigned

tensor([1, 2, 2])

In [27]:
tensor = tensor - 10
tensor

tensor([-9, -8, -8])

In [28]:
tensor = tensor + 10
tensor

tensor([1, 2, 2])

In [29]:
torch.multiply(tensor, 10)

tensor([10, 20, 20])

In [30]:
tensor

tensor([1, 2, 2])

In [31]:
torch.mul(tensor, 10)

tensor([10, 20, 20])

In [32]:
tensor

tensor([1, 2, 2])

In [33]:
tensor * tensor

tensor([1, 4, 4])

## Matrix multiplication

In [34]:
# main two rules for matrix multiplication
# 1. inner dims must match
# 2. resulting matrix has the shape of the outer dims
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [35]:
# element-wise multiplication
# [1*1, 2*2, 3*3] = [1, 4, 9]
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# matrix multiplication
# [1*1 + 2*2 + 3*3] = [14]
tensor @ tensor # OR tensor.matmul(tensor)

tensor(14)

In [37]:
# transposing
# torch.transpose(input, dim0, dim1) -> input is the desired tensor to transpose. dim0 and dim1 are the dims to be swapped.
# tensor.T where tensor is the desired tensor to transpose.
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
torch.mm(tensor_A, tensor_B.T) # shorthand for tensor.matmul

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
torch.manual_seed(42)
linear = torch.nn.Linear(
    in_features=2, # matches the inner dim of the input
    out_features=6 # matches the outer dim of the output
)

x = tensor_A
output = linear(x) # (3, 2) x (2, 6) => (3, 6)
print(f"{x.shape=}")
print(f"{output.shape=}")
print(output)


x.shape=torch.Size([3, 2])
output.shape=torch.Size([3, 6])
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)


## Finding the min, max, mean, sum

In [43]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
print(f"{x.min()=}")
print(f"{x.max()=}")
print(f"{x.sum()=}")
print(f"{x.mean()=}")

x.min()=tensor(0)
x.max()=tensor(90)
x.sum()=tensor(450)


RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
print(f"{x.type(torch.float32).mean()=}") # some methods require tensors to be in torch.float32 or another specific dtype.

x.type(torch.float32).mean()=tensor(45.)


In [47]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [48]:
tensor = torch.arange(0, 100, 10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
tensor.argmax()

tensor(9)

In [50]:
tensor.argmin()

tensor(0)

## Changing dtype

In [53]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [52]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16.dtype

torch.float16

In [54]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8.dtype

torch.int8

In [ ]:
# the lower the number, the less precise the computer stores the value. with a lower amount of storage, results in faster computation and a smaller overall model. mobile-based NNs often operate with 8-bit ints, smaller and faster but less accurate than float32.

## Reshaping, stacking, squeezing, and unsqueezing

In [55]:
# Oh boy do I need this section
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1, 7) # add an extra dimension
x_reshaped, x_reshaped.shape # not guaranteed whether or not reshaped shares its data or is a new tensor altogether.

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [57]:
# change view
# torch.view creates a view of the original tensor. the new tensor ALWAYS shares its data with the original tensor. if you change the original tensor, the viewed tensor will change and vice versa. like aliasing.
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [58]:
x.fill_(1)
z

tensor([[1., 1., 1., 1., 1., 1., 1.]])

In [59]:
x_reshaped

tensor([[1., 1., 1., 1., 1., 1., 1.]])

In [63]:
x = torch.arange(1., 8.)
x_stacked = torch.stack([x, x, x, x], dim=0) # since x.shape is [7], this creates a tensor w shape [4, 7]
x_stacked, x_stacked.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.],
         [1., 2., 3., 4., 5., 6., 7.],
         [1., 2., 3., 4., 5., 6., 7.],
         [1., 2., 3., 4., 5., 6., 7.]]),
 torch.Size([4, 7]))

In [64]:
x = torch.arange(1., 8.)
x_stacked = torch.stack([x, x, x, x], dim=1) # since x.shape is [7], this creates a tensor w shape [7, 4]
x_stacked, x_stacked.shape

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.]]),
 torch.Size([7, 4]))

In [ ]:
print(f"")