In [65]:
import torch
torch.__version__

'2.11.0'

## Basics: scalars -> vectors -> matrices -> tensors

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor(
    [
        [7,8],
        [9,10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
])
TENSOR
print(f"{TENSOR.ndim=}")
print(f"{TENSOR.shape=}")

TENSOR.ndim=3
TENSOR.shape=torch.Size([1, 3, 3])


## Random tensors, zero tensors, ones tensors

In [13]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.6605, 0.5743, 0.0185, 0.8207],
         [0.2551, 0.9097, 0.8133, 0.2726],
         [0.9309, 0.0629, 0.5968, 0.2846]]),
 torch.float32)

In [15]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.ndim, random_image_size_tensor.dtype

(3, torch.float32)

In [16]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [18]:
zero_to_ten = torch.arange(0, 10, 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeros = torch.zeros_like(input=zero_to_ten) # mocking the same shape as the zero_to_ten tensor
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [21]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None, # defaults to None. torch.float32
    device=None, # defaults to None, using the default tensor type
    requires_grad=False # if True, operations performed on the tensor are recorded
)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [22]:
float_16_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float16 # torch.half also works
)
float_16_tensor.dtype

torch.float16

## Finding out details

In [23]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"{some_tensor.shape=}")
print(f"{some_tensor.dtype=}")
print(f"{some_tensor.device=}")

tensor([[0.4844, 0.0439, 0.8052, 0.2640],
        [0.8606, 0.3264, 0.4712, 0.4204],
        [0.6529, 0.4295, 0.3160, 0.5547]])
some_tensor.shape=torch.Size([3, 4])
some_tensor.dtype=torch.float32
some_tensor.device=device(type='cpu')


In [ ]:
# little song: what, what, where? what shape, what datatype, what device?

## Manipulating tensors (operations!)

In [24]:
tensor = torch.tensor([1, 2, 2])
tensor + 10

tensor([11, 12, 12])

In [25]:
tensor * 10

tensor([10, 20, 20])

In [26]:
tensor
# tensors don't change unless reassigned

tensor([1, 2, 2])

In [27]:
tensor = tensor - 10
tensor

tensor([-9, -8, -8])

In [28]:
tensor = tensor + 10
tensor

tensor([1, 2, 2])

In [29]:
torch.multiply(tensor, 10)

tensor([10, 20, 20])

In [30]:
tensor

tensor([1, 2, 2])

In [31]:
torch.mul(tensor, 10)

tensor([10, 20, 20])

In [32]:
tensor

tensor([1, 2, 2])

In [33]:
tensor * tensor

tensor([1, 4, 4])

## Matrix multiplication

In [34]:
# main two rules for matrix multiplication
# 1. inner dims must match
# 2. resulting matrix has the shape of the outer dims
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [35]:
# element-wise multiplication
# [1*1, 2*2, 3*3] = [1, 4, 9]
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# matrix multiplication
# [1*1 + 2*2 + 3*3] = [14]
tensor @ tensor # OR tensor.matmul(tensor)

tensor(14)

In [37]:
# transposing
# torch.transpose(input, dim0, dim1) -> input is the desired tensor to transpose. dim0 and dim1 are the dims to be swapped.
# tensor.T where tensor is the desired tensor to transpose.
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
torch.mm(tensor_A, tensor_B.T) # shorthand for tensor.matmul

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
torch.manual_seed(42)
linear = torch.nn.Linear(
    in_features=2, # matches the inner dim of the input
    out_features=6 # matches the outer dim of the output
)

x = tensor_A
output = linear(x) # (3, 2) x (2, 6) => (3, 6)
print(f"{x.shape=}")
print(f"{output.shape=}")
print(output)


x.shape=torch.Size([3, 2])
output.shape=torch.Size([3, 6])
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)


## Finding the min, max, mean, sum

In [43]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
print(f"{x.min()=}")
print(f"{x.max()=}")
print(f"{x.sum()=}")
print(f"{x.mean()=}")

x.min()=tensor(0)
x.max()=tensor(90)
x.sum()=tensor(450)


RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
print(f"{x.type(torch.float32).mean()=}") # some methods require tensors to be in torch.float32 or another specific dtype.

x.type(torch.float32).mean()=tensor(45.)


In [47]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [48]:
tensor = torch.arange(0, 100, 10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
tensor.argmax()

tensor(9)

In [50]:
tensor.argmin()

tensor(0)

## Changing dtype

In [53]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [52]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16.dtype

torch.float16

In [54]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8.dtype

torch.int8

In [ ]:
# the lower the number, the less precise the computer stores the value. with a lower amount of storage, results in faster computation and a smaller overall model. mobile-based NNs often operate with 8-bit ints, smaller and faster but less accurate than float32.

## Reshaping, stacking, squeezing, and unsqueezing

In [66]:
# Oh boy do I need this section
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [67]:
x_reshaped = x.reshape(1, 7) # add an extra dimension
x_reshaped, x_reshaped.shape # not guaranteed whether or not reshaped shares its data or is a new tensor altogether.

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [68]:
# change view
# torch.view creates a view of the original tensor. the new tensor ALWAYS shares its data with the original tensor. if you change the original tensor, the viewed tensor will change and vice versa. like aliasing.
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [69]:
x.fill_(1)
z

tensor([[1., 1., 1., 1., 1., 1., 1.]])

In [70]:
x_reshaped

tensor([[1., 1., 1., 1., 1., 1., 1.]])

In [71]:
x = torch.arange(1., 8.)
x_stacked = torch.stack([x, x, x, x], dim=0) # since x.shape is [7], this creates a tensor w shape [4, 7]
x_stacked, x_stacked.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.],
         [1., 2., 3., 4., 5., 6., 7.],
         [1., 2., 3., 4., 5., 6., 7.],
         [1., 2., 3., 4., 5., 6., 7.]]),
 torch.Size([4, 7]))

In [72]:
x = torch.arange(1., 8.)
x_stacked = torch.stack([x, x, x, x], dim=1) # since x.shape is [7], this creates a tensor w shape [7, 4]
x_stacked, x_stacked.shape

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.]]),
 torch.Size([7, 4]))

In [73]:
# removing all single dimensions from a tensor. squeeze the tensor to only have dimensions over 1
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()

print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 1., 1., 1., 1., 1., 1.]])
Previous shape: torch.Size([1, 7])
New tensor: tensor([1., 1., 1., 1., 1., 1., 1.])
New shape: torch.Size([7])


In [74]:
# to reverse torch.squeeze, you can do torch.unsqueeze to add a dim=1 at a specific index.
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}") # expecting a tensor of shape [1, 7]

Previous tensor: tensor([1., 1., 1., 1., 1., 1., 1.])
Previous shape: torch.Size([7])
New tensor: tensor([[1., 1., 1., 1., 1., 1., 1.]])
New shape: torch.Size([1, 7])


In [ ]:
# can also rearrange the order of axes values with torch.permute(input, dims)
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0.

print(f"Previous shape: {x_original.shape}") # [224, 224, 3]
print(f"New shape: {x_permuted.shape}") # expecting [3, 224, 224]
# permuting shares a VIEW (sharing the same data as the original), so essentially like an alias

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)
Once again this is a section I desperately need

In [78]:
x = torch.arange(1, 10).reshape(1, 3, 3) # this creates a tensor [1, 2, 3, 4, 5, 6, 7, 8, 9] of shape [9]. then reshapes it into [1, 3, 3]
x.shape

torch.Size([1, 3, 3])

In [79]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [80]:
# indexing values goes outer -> inner dim
# index bracket by bracket
print(f"First square bracket: {x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [81]:
# can use : to specify "all values in this dim" and then , to specify another dimension
# get all values of 0th dim and then 0 index of 1st dim
x[:, 0]

tensor([[1, 2, 3]])

In [82]:
# inherently the above is the same as the below
x[:, 0, :]

tensor([[1, 2, 3]])

In [85]:
# but cannot do the below
x[,0,]

SyntaxError: invalid syntax (1832162477.py, line 2)

In [ ]:
# get all values of 0th and 1st dims but only index 1 of 2nd dim
x[:, :, 1] # notice that this grabs the vertical column of the matrix

tensor([[2, 5, 8]])

In [87]:
# get all values of the 0th dim but only the 1 index val of the 1st and 2nd dim
x[:, 1, 1]

tensor([5])

In [88]:
# get index 0 of 0th and 1st dim and all values of 2nd dim
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch and NumPy

In [2]:
import numpy as np
import torch
# two main methods to transition back and forth
# torch.from_numpy(ndarray)
# torch.Tensor.numpy()
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [5]:
# note that by default, numpy arrays are created with the dtype float64. if converted to a tensor, keeps float64.
# however, many pytorch calculations default to using float32.
# want to convert numpy array (float64) -> tensor (float32), then must cast it.
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype

torch.float32

In [6]:
# change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [7]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # will be float32
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [8]:
# change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

In [9]:
# two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A: {random_tensor_A}")
print(f"Tensor B: {random_tensor_B}")
print(f"Does Tensor A equal Tensor B anywhere? {random_tensor_A == random_tensor_B}")

Tensor A: tensor([[0.8479, 0.6264, 0.1555, 0.1504],
        [0.5233, 0.8041, 0.6940, 0.7227],
        [0.4443, 0.9787, 0.3716, 0.0400]])
Tensor B: tensor([[0.4533, 0.5484, 0.0749, 0.5125],
        [0.3745, 0.0954, 0.6750, 0.2441],
        [0.1451, 0.3864, 0.1052, 0.5658]])
Does Tensor A equal Tensor B anywhere? tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 60
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# have to reset the seed every time a new rand() is called.
torch.random.manual_seed(seed=RANDOM_SEED) # if this line is commented out, then tensor_D is different to tensor_C.
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C: {random_tensor_C}")
print(f"Tensor D: {random_tensor_D}")
print(f"Does Tensor C equal Tensor D anywhere?")
random_tensor_C == random_tensor_D

Tensor C: tensor([[0.0236, 0.3107, 0.8581, 0.4991],
        [0.7348, 0.6979, 0.4319, 0.7147],
        [0.1445, 0.5976, 0.9530, 0.7818]])
Tensor D: tensor([[0.0236, 0.3107, 0.8581, 0.4991],
        [0.7348, 0.6979, 0.4319, 0.7147],
        [0.1445, 0.5976, 0.9530, 0.7818]])
Does Tensor C equal Tensor D anywhere?


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [4]:
import torch

In [1]:
!nvidia-smi

Fri Apr 24 22:44:03 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
torch.cuda.is_available()

True

In [4]:
# set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
torch.cuda.device_count()

1

In [ ]:
torch.backends.mps.is_available() # running on apple silicon!!

False

In [7]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

## Putting tensors and models on the GPU

In [ ]:
# using to(device) returns a copy of that tensor, the same tensor will be on CPU and GPU. to overwrite, reassign them!
tensor = torch.tensor([1, 2, 3]) # default on cpu
print(tensor, tensor.device)

tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device) # cuda:0 means its stored on the 0th GPU available. GPUs are 0 indexed.


tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


In [9]:
# try to apply numpy on tensor_on_gpy
# if tensor is on gpu, cannot transform to numpy
tensor_on_gpu.numpy() # raises error

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [10]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [11]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')